pub mod integrate_simpsons_rule;
pub mod integrate_trapezoidal_rule;

pub use integrate_simpsons_rule::integrate_simpsons_rule;
pub use integrate_simpsons_rule::integrate_simpsons_rule_adaptive;
pub use integrate_trapezoidal_rule::integrate_trapezoidal_rule;
pub use integrate_trapezoidal_rule::integrate_trapezoidal_rule_adaptive;
